---
# tasks file for ansible-role-splunk

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: proxy != False

- name: "Test Access to Heavy Forwarder Server"
  ansible.builtin.uri:
    url: "https://{{ heavy_forwarder_host }}:{{ heavy_forwarder_port }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: proxy != False

- name: "Create Splunk service account"
  ansible.builtin.user:
    name: "{{ splunk_account }}"
    comment: "Splunk Server"
    password: "{{ splunk_password }}"
    shell: /bin/bash

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/splunk/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/splunk/{{ package_name }}"
  register: package

- name: "Download installer package from local repository"
  ansible.builtin.get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/splunk/"
    validate_certs: no
    mode: 0777
  when: package.stat.exists != True

- name: "Install package (RHEL - yum)"
  ansible.builtin.yum:
    name: "/root/software/splunk/{{ package_name }}"
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] <= '7'
    - '"splunkforwarder" not in ansible_facts.packages'

- name: "Install package (RHEL - dnf)"
  ansible.builtin.dnf:
    name: "/root/software/splunk/{{ package_name }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] >= '8'
    - '"splunkforwarder" not in ansible_facts.packages'

- name: "Install package (Debian)"
  ansible.builtin.apt:
    deb: "/root/software/splunk/{{ package_name }}"
    state: present
  when:
    - ansible_facts['os_family'] == 'Debian'
    - '"splunkforwarder" not in ansible_facts.packages'

- name: "Test for existence deploymentclient.conf file"
  ansible.builtin.stat:
    path: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
  register: file_exists

- name: "Create deploymentclient.conf file"
  ansible.builtin.copy:
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    content: |
      [target-broker:deploymentServer]
      targetUri = {{ heavy_forwarder_host }}:{{ heavy_forwarder_port }}
  when: file_exists.stat is defined and file_exists.stat.exists == False

- name: "Create user-seed.conf file"
  ansible.builtin.copy:
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    content: |
      [user_info]
      USERNAME={{ splunk_account }}
      PASSWORD={{ splunk_password }}

- name: "Start the Splunk Universal Forwarder Service"
  ansible.builtin.command: ./splunk start --no-prompt --accept-license --answer-yes
  args:
    chdir: "/opt/splunkforwarder/bin/"

- name: "Wait 30 seconds"
  ansible.builtin.wait_for:
    timeout: 30
  delegate_to: localhost

- name: "Stop the Splunk Universal Forwarder Service"
  ansible.builtin.command: ./splunk stop
  args:
    chdir: "/opt/splunkforwarder/bin/"

- name: "Test for existence server.conf"
  ansible.builtin.stat:
    path: /opt/splunkforwarder/etc/system/local/server.conf
  register: file_exists
  when: proxy != False

- name: "Update server.conf to point to Proxy Server"
  ansible.builtin.blockinfile:
    path: /opt/splunkforwarder/etc/system/local/server.conf
    insertafter: "^pass4SymmKey ="
    state: present
    block: |

      [proxyConfig]
      http_proxy = {{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}
      https_proxy = {{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}

  when: file_exists.stat is defined and file_exists.stat.exists and proxy != False

- name: "Change folder permissions of Splunk Universal Forwarder directory"
  ansible.builtin.command: find . -type d -exec chown {{ splunk_account }}:{{ splunk_account }} {} \;
  args:
    chdir: "/opt/splunkforwarder/"

- name: "Change file permissions of Splunk Universal Forwarder directory"
  ansible.builtin.command: find . -type f -exec chown {{ splunk_account }}:{{ splunk_account }} {} \;
  args:
    chdir: "/opt/splunkforwarder/"

- name: "Start the Splunk Universal Forwarder Service"
  ansible.builtin.command: ./splunk start --no-prompt --accept-license --answer-yes
  args:
    chdir: "/opt/splunkforwarder/bin/"

- name: "Enable the Splunk Universal Forwarder Service at boot"
  ansible.builtin.command: ./splunk enable boot-start -systemd-managed 1
  args:
    chdir: "/opt/splunkforwarder/bin/"
