---
# tasks file for ansible-role-splunk

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_protocol }}://{{ proxy_host }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: proxy != False

- name: "Test Access to Heavy Forwarder Server"
  ansible.builtin.uri:
    url: "https://{{ heavy_forwarder }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]

#- name: "Gather the package facts"
#  ansible.builtin.package_facts:
#    manager: auto
#  when:
#    - ansible_facts['packages'] is not defined

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from upgrade playbook"
  ansible.builtin.include_tasks: upgrade.yaml
  when:
    - upgrade is defined
    - upgrade | bool
