---
# Upgrade tasks file for ansible-role-splunk

- name: "Check for SPLUNK_HOME Environment Variable"
  ansible.builtin.shell:
    cmd: . /etc/profile && (env | grep -iP "SPLUNK_HOME" | awk 'OFS="|" { print $2 }')
  #when:
    #- ansible_facts.ansible_env.SPLUNK_HOME is defined
    #- ansible_facts["env"].SPLUNK_HOME
    #- ansible_facts.env.SPLUNK_HOME exists

#- name: "Get Facts about existing installation"
