---
# Upgrade tasks file for ansible-role-splunk

- name: "Check for SPLUNK_HOME Environment Variable"
  ansible.builtin.shell:
    cmd: . /etc/profile && (env | grep -iP "SPLUNK_HOME")
  register: result
  ignore_errors: true

- name: "Set Facts for SPLUNK_HOME Environment Variable"
  ansible.builtin.set_fact:
    splunk_home: "{{ result.stdout | split('=') | last }}"
  #when:
    #- ansible_facts.ansible_env.SPLUNK_HOME is defined
    #- ansible_facts["env"].SPLUNK_HOME
    #- ansible_facts.env.SPLUNK_HOME exists

#- name: "Get Facts about existing installation"
